# -*- coding: utf-8 -*-
"""ConvertZip

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zt5nMTWpOhfp1D4jWycAi4-pK9Jj-mnD
"""

def get_lat_long(postal_code):
  !pip install pgeocode
  import pgeocode
  nomi = pgeocode.Nominatim('us') # Must be in US
  if len(postal_code) != 5:
    print('Invalid Postal Code')
    return
  a = nomi.query_postal_code(postal_code)
  return a['latitude'], a['longitude']